import type { Metadata } from "next";
import "./globals.css";
import { fontCode, fontDoto } from "../../public/fonts/index";

export const metadata: Metadata = {
  title: "Quetris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontDoto.variable} ${fontCode.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
